### ISSUE TITLE
Trouble only viewing one track at a stop

### ISSUE THREAD

**Issue by graaahn** [bureus/MMM-Vasttrafik-PublicTransport#11]
Hi,

Super nice module! 
When retrieving the track id's, I am only choosing the ID for track A at my stop, but the module is still showing all tracks.. Have I done anyting wrong? Or is choosing only one track not possible?

BR
Grahn

**Comment by bureus** [comment]
@graaahn : Thanks for your kind words. That's currently not supported by the module. But I can easily fix it. So give me a couple of hours and a new patch will be released so that you can filter board based on track :)

**Comment by bureus** [comment]
@graaahn : So I have released a feature now that allows you to filter on "track", "direction", "line" or "type". This will give you that possibility to only show track = A or line = 2 for example. So dont use any track id or similar, just use the normal stopId and configurations to the module. 

In order to get this to work, you first need to update the module, see section "Update". After that has been completed you need to change your configs according to specifications described in section "Configuration". See filterAttr and filterKey. Examples of how to do that is added under section "Filtered board".

So in short your config should look something like this: 
``
    {
            module: "MMM-Vasttrafik-PublicTransport",
            position: "bottom_left",
            header: "Västtrafik",
            config: {
                     stopIds: ["your_stop_ids"], 
                     appKey: "your_app_key", 
                     appSecret: "your_app_secret", 
                     debug: false,                
                     sortBy: "track",              
                     refreshRate: "20000",          
                     trafficSituations: true,     
                    filterAttr: "track",           
                    filterKey: "A"            
            }
        },
``
Please reach out again if it dosent work :)

**Comment by graaahn** [comment]
Thank you so much! Works perfectly now!

**Comment by Gnarga** [comment]
When filtering on type, is it "train", "bus" and so on? And filtering on direction?
Trying to filter to only show trains from Trollhättan Resecentrum to Göteborg Central, any help would be appreciated!
