### ISSUE TITLE
Limit bus destination width

### ISSUE THREAD

**Issue by retroflex** [bureus/MMM-Vasttrafik-PublicTransport#3]
I had a new idea... how about truncating the bus destinations to a max number of characters (configurable)? Some buses have long destinations, which messes up the layout.

Example:
GRÖN: Höga Hallar via Mölnlycketerminalen

Set config: max-characters=15...
GRÖN: Höga Hallar via...

Default 0 would mean to show all characters.

Alternatively a config to strip everything after "via", but it seems a bit arbitrary. What do you think?
Another way would be to change the font size, but I'm not really that good at css.

**Comment by bureus** [comment]
Great idea, resolved it in latest commit. Was actually set before to 200 px but due to how tables are rendered i was forced to wrap destination name within a div. So now default is 200px, but you can control it thru the new board setting maxPxWidth if you want it smaller, see read me.

```
 board: {
                        destination: {
                            maxPxWidth: 150       // Optional. Force max width for destination names.
                        }
                    }, 
```

Also please try out the new traffic situation banner :) See Prerequisites 2.1

**Comment by retroflex** [comment]
Great, thanks! Looks much better on my mirror now.

I've also switched on traffic situations, so I'll just wait until I have a situation :) Looks good in the readme though!
